# Generated by Django 5.0.7 on 2024-07-17 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_profilemodel_user_name_profilemodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupModel',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='username',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
