# Generated by Django 5.0.7 on 2024-07-17 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_signupmodel_remove_profilemodel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
