# Generated by Django 5.0.7 on 2024-07-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
