# Generated by Django 5.0.7 on 2024-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_remove_reply_comment_remove_reply_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
